# Travis CI script based on https://github.com/pypa/python-manylinux-demo

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=arpa2/build-pip
           PYTHON=python
           PIP=pip
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=arpa2/build-pip3
           PYTHON=python3
           PIP=pip3

install:
  - docker pull $DOCKER_IMAGE

# Last statement is the ONLY ONE whose output matters
script:
  - docker run --rm -e PLAT=$PLAT -e PYTHON=$PYTHON -e PIP=$PIP -v `pwd`:/io $DOCKER_IMAGE /io/contrib/travis-ci/build-distro.sh
